CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    EMAIL CHARACTER VARYING(100) UNIQUE NOT NULL,
    PASSWORD CHARACTER VARYING(100) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    NAME CHARACTER VARYING(100),
    GENDER CHAR(1),
    BIRTHDAY DATE,
    JOB CHARACTER VARYING(50),
    COUNTRY CHARACTER VARYING(50),
    PHONE CHAR(11),
    ADDRESS CHARACTER VARYING(300),
    INTRODUCE CHARACTER VARYING(200),
    STORY CHARACTER VARYING(4000),
    AVATAR_SRC CHARACTER VARYING(200),
    BACKGROUND_SRC CHARACTER VARYING(200),
    IS_ONLINE CHAR(1),
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE VERIFIES (
    VERIFY_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TOKEN CHARACTER VARYING(10) UNIQUE NOT NULL,
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE FOLLOWS (
    FOLLOW_ID SERIAL PRIMARY KEY,
    SOURCE_ID INT NOT NULL,
    TARGET_ID INT NOT NULL,
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (SOURCE_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (TARGET_ID) REFERENCES USERS(USER_ID)
);


