CREATE TABLE POSTS (
    POST_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    TEXT CHARACTER VARYING(2000),
    STATUS CHAR(1) NOT NULL,
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE COMMENTS (
    COMMENT_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL,
    POST_ID INT,
    PARENT_ID INT,
    REPLY_ID INT,
    TEXT CHARACTER VARYING(2000),
    IS_DELETE CHAR(1),
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    UPDATE_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID),
    FOREIGN KEY (PARENT_ID) REFERENCES COMMENTS(COMMENT_ID),
    FOREIGN KEY (REPLY_ID) REFERENCES COMMENTS(COMMENT_ID)
);

