CREATE TABLE BOOKMARKS (
    BOOKMARK_ID SERIAL PRIMARY KEY,
    POST_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (POST_ID) REFERENCES POSTS(POST_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE CHAT_ROOMS (
    CHAT_ROOM_ID SERIAL PRIMARY KEY,
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE MESSAGES (
    MESSAGE_ID SERIAL PRIMARY KEY,
    SEND_ID INT NOT NULL,
    RECEIVE_ID INT NOT NULL,
    CHAT_ROOM_ID INT NOT NULL,
    TEXT CHARACTER VARYING(200),
    FILE CHARACTER VARYING(100),
    IMAGE CHARACTER VARYING(100),
    VIDEO CHARACTER VARYING(100),
    REG_DATE TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (SEND_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (RECEIVE_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (CHAT_ROOM_ID) REFERENCES CHAT_ROOMS(CHAT_ROOM_ID)
);